spring.application.name=queroMaisPizza
spring.datasource.url=jdbc:postgresql://localhost:5432/pizzaria_db
spring.datasource.username=postgres
spring.datasource.password=Mateus983212.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true